In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"E:\python\Project\Telco_customer_churn.csv")
df

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,United States,California,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,Female,...,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No,0,45,5306,NaN
7039,6840-RESVB,1,United States,California,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,Male,...,One year,Yes,Mailed check,84.80,1990.5,No,0,59,2140,NaN
7040,2234-XADUH,1,United States,California,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,Female,...,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,71,5560,NaN
7041,4801-JZAZL,1,United States,California,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,Female,...,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,59,2793,NaN
7042,3186-AJIEK,1,United States,California,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,Male,...,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,38,5097,NaN

In [3]:
df.shape

(7043, 33)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   str
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), str(24)
memory usage: 2.9 MB

In [5]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [6]:
df['CustomerID'].duplicated().sum()

np.int64(0)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['Total Charges'].value_counts().head(10)

Total Charges
20.2     11
         11
19.75     9
19.9      8
19.65     8
20.05     8
19.55     7
45.3      7
20.15     6
19.45     6
Name: count, dtype: int64

In [9]:
df[df['Total Charges'].str.strip() == '']['Total Charges'].count()

np.int64(11)

In [10]:
df['Total Charges'] = df['Total Charges'].str.strip()

In [11]:
df['Total Charges'] = pd.to_numeric(
    df['Total Charges'],
    errors='coerce'
)

In [12]:
df['Total Charges'].dtype

dtype('float64')

In [13]:
df['Total Charges'].isnull().sum()

np.int64(11)

In [14]:
df[df['Total Charges'].isnull()][
    ['CustomerID', 'Tenure Months', 'Monthly Charges', 'Total Charges', 'Churn Label']
]

      CustomerID  Tenure Months  Monthly Charges  Total Charges Churn Label
2234  4472-LVYGI              0            52.55            NaN          No
2438  3115-CZMZD              0            20.25            NaN          No
2568  5709-LVOEQ              0            80.85            NaN          No
2667  4367-NUYAO              0            25.75            NaN          No
2856  1371-DWPAZ              0            56.05            NaN          No
4331  7644-OMVMY              0            19.85            NaN          No
4687  3213-VVOLG              0            25.35            NaN          No
5104  2520-SGTTA              0            20.00            NaN          No
5719  2923-ARZLG              0            19.70            NaN          No
6772  4075-WKNIU              0            73.35            NaN          No
6840  2775-SEFEE              0            61.90            NaN          No

In [15]:
df['Total Charges'] = df['Total Charges'].fillna(0)

In [16]:
df['Total Charges'].isnull().sum()

np.int64(0)

In [17]:
def categorize_tenure(tenure):
    if tenure <= 12:
        return 'Short-term'
    elif tenure <= 36:
        return 'Mid-term'
    else:
        return 'Long-term'

In [18]:
df['Customer Segmentation'] = df['Tenure Months'].apply(categorize_tenure)

In [19]:
df[['Tenure Months', 'Customer Segmentation']].head(20)

    Tenure Months Customer Segmentation
0               2            Short-term
1               2            Short-term
2               8            Short-term
3              28              Mid-term
4              49             Long-term
5              10            Short-term
6               1            Short-term
7               1            Short-term
8              47             Long-term
9               1            Short-term
10             17              Mid-term
11              5            Short-term
12             34              Mid-term
13             11            Short-term
14              2            Short-term
15             15              Mid-term
16              8            Short-term
17             18              Mid-term
18              9            Short-term
19              1            Short-term

In [20]:
print(categorize_tenure(3))
print(categorize_tenure(12))
print(categorize_tenure(13))
print(categorize_tenure(36))
print(categorize_tenure(37))

Short-term
Short-term
Mid-term
Mid-term
Long-term

In [21]:
df['Customer Segmentation'].value_counts()

Customer Segmentation
Long-term     3001
Short-term    2186
Mid-term      1856
Name: count, dtype: int64

In [22]:
df[['Tenure Months',
    'Monthly Charges',
    'Total Charges',
    'Churn Value',
    'Churn Score',
    'CLTV']].dtypes

Tenure Months        int64
Monthly Charges    float64
Total Charges      float64
Churn Value          int64
Churn Score          int64
CLTV                 int64
dtype: object

In [23]:
df.isnull().sum().sort_values(ascending=False)

Churn Reason             5174
CustomerID                  0
Count                       0
Country                     0
City                        0
State                       0
Lat Long                    0
Latitude                    0
Longitude                   0
Zip Code                    0
Senior Citizen              0
Partner                     0
Dependents                  0
Tenure Months               0
Phone Service               0
Multiple Lines              0
Internet Service            0
Gender                      0
Online Security             0
Online Backup               0
Tech Support                0
Device Protection           0
Streaming Movies            0
Contract                    0
Paperless Billing           0
Streaming TV                0
Payment Method              0
Monthly Charges             0
Churn Label                 0
Total Charges               0
Churn Value                 0
Churn Score                 0
CLTV                        0
Customer Segmentation       0
dtype: int64

In [24]:
clean_file_path = r"E:\python\Project\Telco_customer_churn_cleaned.csv"

df.to_csv(clean_file_path, index=False)

In [25]:
df_check = pd.read_csv(clean_file_path)

print(df_check.shape)

(7043, 34)

In [26]:
df_check.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason,Customer Segmentation
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer,Short-term
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved,Short-term
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Yes,Electronic check,99.65,820.50,Yes,1,86,5372,Moved,Short-term
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved,Mid-term
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Yes,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices,Long-term